In [1]:
from platform import python_version
print(python_version())
import transformers as tf
print(tf.__version__)

3.7.4


ModuleNotFoundError: No module named 'transformers'

In [2]:
import torch
torch.__version__

'1.5.1'

In [2]:
!pip install transformers==3.0.2

  Using cached sacremoses-0.0.43.tar.gz (883 kB)
  Created wheel for sacremoses: filename=sacremoses-0.0.43-py3-none-any.whl size=893260 sha256=d526e71dab1f53a0584012d44f8c082dd7e9807b974d05bc0daf3b4ca9153919
  Stored in directory: c:\users\sonwang.redmond\appdata\local\pip\cache\wheels\69\09\d1\bf058f7d6fa0ecba2ce7c66be3b8d012beb4bf61a6e0c101c0
Successfully built sacremoses


You should consider upgrading via the 'c:\users\sonwang.redmond\appdata\local\continuum\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import torch

torch.manual_seed(999)

x1 = torch.rand(3,4)
x2 = torch.rand(3,4)
y = torch.cat((x1, x2), dim =1)
x1,x2, y

(tensor([[0.6776, 0.6531, 0.0457, 0.9424],
         [0.4925, 0.9985, 0.7585, 0.0317],
         [0.2769, 0.9590, 0.0498, 0.1786]]),
 tensor([[0.4095, 0.5523, 0.9228, 0.0484],
         [0.8004, 0.3307, 0.5326, 0.2070],
         [0.2271, 0.8472, 0.7639, 0.7220]]),
 tensor([[0.6776, 0.6531, 0.0457, 0.9424, 0.4095, 0.5523, 0.9228, 0.0484],
         [0.4925, 0.9985, 0.7585, 0.0317, 0.8004, 0.3307, 0.5326, 0.2070],
         [0.2769, 0.9590, 0.0498, 0.1786, 0.2271, 0.8472, 0.7639, 0.7220]]))

In [4]:
import transformers as tf
tf.__version__
#'3.0.2'

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
len(tokenizer)                                                                                                                                                                                                                                                                                                                                                                                                           #30522
x = '[AGENTSTART] hello [X_SEP] songsong'  
tokenizer.tokenize(x) 
#['[', 'agents', '##tar', '##t', ']', 'hello', '[', 'x', '_', 'sep', ']', 'songs', '##ong']

['[',
 'agents',
 '##tar',
 '##t',
 ']',
 'hello',
 '[',
 'x',
 '_',
 'sep',
 ']',
 'songs',
 '##ong']

In [5]:
num_added_toks = tokenizer.add_tokens(['[AGENTSTART]','[X_SEP]']) 
tokenizer.tokenize(x) 
#['[agentstart]', 'hello', '[x_sep]', 'songs', '##ong']

['[agentstart]', 'hello', '[x_sep]', 'songs', '##ong']

In [6]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')                                                                                                                                                                                                                                                                                        
num_added_toks = tokenizer.add_special_tokens({'additional_special_tokens': ['[AGENTSTART]','[X_SEP]']}                        )                                                                                                                                                                                                                                                                                                                                                      
tokenizer.tokenize(x)                                                                                                                                                                                                                                                                                                                                                                                                    
#['[AGENTSTART]', 'hello', '[X_SEP]', 'songs', '##ong']

['[AGENTSTART]', 'hello', '[X_SEP]', 'songs', '##ong']

In [7]:
%%time
text = 'This is a cute dog' 
    
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-uncased') 
tokens = bert_tokenizer.tokenize(text)
text_ids = bert_tokenizer.convert_tokens_to_ids(tokens)
print(tokens)
print(text_ids)

['this', 'is', 'a', 'cute', 'dog']
[2023, 2003, 1037, 10140, 3899]
CPU times: user 93.8 ms, sys: 46.9 ms, total: 141 ms
Wall time: 5.51 s


In [8]:
from transformers import RobertaTokenizerFast

In [9]:
%%time

text = 'This is a cute dog'
roberta_tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base')  
tokens = roberta_tokenizer.tokenize(text)
text_ids = roberta_tokenizer.convert_tokens_to_ids(tokens)
print(tokens)
print(text_ids)


['This', 'Ġis', 'Ġa', 'Ġcute', 'Ġdog']
[713, 16, 10, 11962, 2335]
CPU times: user 500 ms, sys: 281 ms, total: 781 ms
Wall time: 23.2 s


In [14]:
text = ['This is a cute dog', 'This is a cute cat but I dont like cat!'] 
tokens = [roberta_tokenizer.tokenize(x) for x in text]
text_ids = [roberta_tokenizer.convert_tokens_to_ids(tk) for tk in tokens]
print(tokens)
print(text_ids)

[['This', 'Ġis', 'Ġa', 'Ġcute', 'Ġdog'], ['This', 'Ġis', 'Ġa', 'Ġcute', 'Ġcat', 'Ġbut', 'ĠI', 'Ġdont', 'Ġlike', 'Ġcat', '!']]
[[713, 16, 10, 11962, 2335], [713, 16, 10, 11962, 4758, 53, 38, 33976, 101, 4758, 328]]


In [25]:
tensor_x = torch.tensor(text_ids[0], dtype=torch.long)
tensor_x

tensor([  713,    16,    10, 11962,  2335])

In [29]:
tensor_x.size(0)

5

In [22]:
torch.tensor(text_ids[1], dtype=torch.long)

tensor([  713,    16,    10, 11962,  4758,    53,    38, 33976,   101,  4758,
          328])

In [19]:
class Numerator:
    def __init__(self, nums):
        self.nums = nums
    
    def __len__(self):
        return len(self.nums)
    
    def __getitem__(self, i):
        return self.nums[i]
    
x = Numerator([x for x in range(0, 1000, 100)])
x[3], x[4]

(300, 400)

In [31]:
roberta_tokenizer.mask_token, roberta_tokenizer.pad_token

('<mask>', '<pad>')