# prerequisite
conda env list
conda activate transV3 # transoformers==3.0.2, python =3.7.7
conda install -c conda-forge jupyterlab or pip install jupyterlab



In [1]:
from platform import python_version
print(python_version())
import transformers as tf
print(tf.__version__)

3.7.4
2.11.0


In [2]:
import torch
torch.__version__

'1.5.1'

In [3]:
import torch

torch.manual_seed(999)

x1 = torch.rand(3,4)
x2 = torch.rand(3,4)
y = torch.cat((x1, x2), dim =1)
x1,x2, y

(tensor([[0.6776, 0.6531, 0.0457, 0.9424],
         [0.4925, 0.9985, 0.7585, 0.0317],
         [0.2769, 0.9590, 0.0498, 0.1786]]),
 tensor([[0.4095, 0.5523, 0.9228, 0.0484],
         [0.8004, 0.3307, 0.5326, 0.2070],
         [0.2271, 0.8472, 0.7639, 0.7220]]),
 tensor([[0.6776, 0.6531, 0.0457, 0.9424, 0.4095, 0.5523, 0.9228, 0.0484],
         [0.4925, 0.9985, 0.7585, 0.0317, 0.8004, 0.3307, 0.5326, 0.2070],
         [0.2769, 0.9590, 0.0498, 0.1786, 0.2271, 0.8472, 0.7639, 0.7220]]))

In [4]:
import torch

torch.manual_seed(999)

x = torch.rand(2,4,4)

print(x)


tensor([[[0.6776, 0.6531, 0.0457, 0.9424],
         [0.4925, 0.9985, 0.7585, 0.0317],
         [0.2769, 0.9590, 0.0498, 0.1786],
         [0.4095, 0.5523, 0.9228, 0.0484]],

        [[0.8004, 0.3307, 0.5326, 0.2070],
         [0.2271, 0.8472, 0.7639, 0.7220],
         [0.7492, 0.3809, 0.5993, 0.1776],
         [0.0750, 0.6554, 0.5502, 0.0341]]])


In [5]:
new_x_shape = x.size()[:-1] + (2,2)
new_x = x.view(new_x_shape)
print(new_x.shape)
print(new_x)

torch.Size([2, 4, 2, 2])
tensor([[[[0.6776, 0.6531],
          [0.0457, 0.9424]],

         [[0.4925, 0.9985],
          [0.7585, 0.0317]],

         [[0.2769, 0.9590],
          [0.0498, 0.1786]],

         [[0.4095, 0.5523],
          [0.9228, 0.0484]]],


        [[[0.8004, 0.3307],
          [0.5326, 0.2070]],

         [[0.2271, 0.8472],
          [0.7639, 0.7220]],

         [[0.7492, 0.3809],
          [0.5993, 0.1776]],

         [[0.0750, 0.6554],
          [0.5502, 0.0341]]]])


In [6]:
y = new_x.permute(0,2,1,3)
print(y.shape)
print(y)

torch.Size([2, 2, 4, 2])
tensor([[[[0.6776, 0.6531],
          [0.4925, 0.9985],
          [0.2769, 0.9590],
          [0.4095, 0.5523]],

         [[0.0457, 0.9424],
          [0.7585, 0.0317],
          [0.0498, 0.1786],
          [0.9228, 0.0484]]],


        [[[0.8004, 0.3307],
          [0.2271, 0.8472],
          [0.7492, 0.3809],
          [0.0750, 0.6554]],

         [[0.5326, 0.2070],
          [0.7639, 0.7220],
          [0.5993, 0.1776],
          [0.5502, 0.0341]]]])


In [7]:
(1,2)+(3,)

(1, 2, 3)

In [8]:
y.nonzero(as_tuple=True)

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 1, 1, 2, 2, 3, 3,
         0, 0, 1, 1, 2, 2, 3, 3]),
 tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
         0, 1, 0, 1, 0, 1, 0, 1]))

In [9]:
z = torch.zeros(4,3)
z[:,-1]=1
z

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [10]:
z.nonzero(as_tuple=True)

(tensor([0, 1, 2, 3]), tensor([2, 2, 2, 2]))

In [11]:
z

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [14]:
import torch
import numpy as np
x = np.array( [0, 2, 7, 6, 3, 1, 4, 5] )
shape = ( 2, 4 )
x.reshape( shape )

array([[0, 2, 7, 6],
       [3, 1, 4, 5]])

In [16]:
tensor_x = torch.Tensor(data)
tensor_x.view(4,-1)

tensor([[0., 2.],
        [7., 6.],
        [3., 1.],
        [4., 5.]])